---
- hosts: jenkins-slave
  become: true

  tasks:
    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
      register: kubectl_install

    - name: Install unzip on Ubuntu
      apt:
        name: unzip

    - name: Install AWSCLI
      shell: |
        sudo yum remove awscli
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
        aws --version
      register: awscli_install

    - name: Configure kubectl for EKS as root
      shell: |
        aws eks --region {{ aws_region }} update-kubeconfig --name {{ eks_cluster_name }}
      when: kubectl_install.rc == 0 # Only run if kubectl installation was successful
      register: kubectl_config_output
      become: true
      become_user: ubuntu

    - name: Print kubectl configuration output
      debug:
        var: kubectl_config_output.stdout
